### ISSUE TITLE
Leave Summary Update Issue

### ISSUE THREAD

**Issue by msf458** [saifuldipak/attendance#15]
Leave Summary not updating when cancelling a leave after get approved. Given this Error:

> [2023-08-02 13:05:30,660] ERROR in app: Exception on /application/cancel/3861 [GET]
Traceback (most recent call last):
  File "/home/saiful/attendance-dev/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saiful/attendance-dev/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saiful/attendance-dev/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saiful/attendance-dev/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saiful/attendance-dev/src/attendance/auth.py", line 73, in wrapped_view
    return view(**kwargs)
  File "/home/saiful/attendance-dev/src/attendance/application.py", line 240, in process
    rv = update_leave_summary(employees, year_start_date, year_end_date)
TypeError: update_leave_summary() takes 2 positional arguments but 3 were given

**Comment by saifuldipak** [comment]
Issue fixed with this commit (9e6e4fde)
