### ISSUE TITLE
Attendance approval by Department head gives error

### ISSUE THREAD

**Issue by saifuldipak** [saifuldipak/attendance#3]
[2022-09-06 08:59:13,431] ERROR in app: Exception on /attendance/application/approval/department [GET]
Traceback (most recent call last):
  File "/home/saiful/attendance-dev/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/saiful/attendance-dev/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/saiful/attendance-dev/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/saiful/attendance-dev/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/saiful/attendance-dev/src/attendance/auth.py", line 72, in wrapped_view
    return view(**kwargs)
  File "/home/saiful/attendance-dev/src/attendance/auth.py", line 112, in wrapped_view
    return view(**kwargs)
  File "/home/saiful/attendance-dev/src/attendance/attendance.py", line 863, in approval_department
    if not manager:
UnboundLocalError: local variable 'manager' referenced before assignment

**Comment by saifuldipak** [comment]
Issue fixed in commit 2817b6f61c48e
